development:
  host: 'flame.mongohq.com'
  port: '27108'
  username: 'mousehouse'
  password: 'mousehouse'
  database: 'app3464023'

test:
  host: localhost
  database: mousehouse_rails_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
